version: "3.8"

services:
  api:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: levisilvaz99/backend-app:v1
    container_name: backend-app
    networks:
      - aplication-login
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_URL=jdbc:postgresql://ec2-67-202-36-228.compute-1.amazonaws.com:5432/d8eqg7d4d8isf8
      - POSTGRES_USER=vvhbifwchrsmkf
      - POSTGRES_PASSWORD=b092dc03a7cd54260b8fc1935bd58cdbf26d8a59b78977ff4cd8c2efd504c2f0
      - POSTGRES_DB=postgres-db
    ports:
      - "5432:5432"
    networks:
      - aplication-login
    volumes:
      - pgdata:/var/lib/postgres/data/

networks:
  aplication-login:
    driver: bridge

volumes:
  pgdata: